language: ruby
sudo: false
rvm:
- 2.0.0
- 1.9.3
env:
- CHEF_VERSION=11.6.0.5
- CHEF_VERSION=12.2.1
before_script: bundle exec berks install
script: bundle exec strainer test --except kitchen
notifications:
  slack:
    secure: g8fLCO0HeAPlQGRPt6dV/2850zLwMHb6sQESTXVudGHINlLJBdHY/j2DkKc/q5Avl8C5wAAaqowwXYtbPOaXr3NYCBnvljheF7eiGvHxc0ARFm536IukqAarmeeWYmD30dx3UyLbpnhOChtWkSityOMpp9esA0iN4ZlPLu+2O58=
